version: '3.8'

services:

  sql-server:
    user: root
    container_name: sql-server-2019-polytechnics-prod-1
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - SQL_VOLUME_PATH=${SQL_VOLUME_PATH}
    ports:
      - "1433:1433"
    volumes:
      - ${SQL_VOLUME_PATH}:/var/opt/mssql/data
    networks:
      - polytechnics-network

  web-api-polytechnics:
    build: 
      context: .
      dockerfile: ./WebApiMdm/dockerfile
    container_name: web-api-polytechnics-api-prod-1
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ConnectionString=Data Source=sql-server;Initial Catalog=master;User Id=sa;Password=${MSSQL_SA_PASSWORD};
    depends_on:
      - sql-server
    networks:
      - polytechnics-network
    # stdin_open: true
    # tty: true

  angular-ui:
    build:
      context: .
      dockerfile: ./MvmNewUI/dockerfile
    container_name: angular-polytechnics-prod-1
    ports:
      - "1080:80"
    depends_on:
      - web-api-polytechnics
    networks:
      - polytechnics-network
    # stdin_open: true
    # tty: true

networks:
  polytechnics-network:
    driver: bridge
