version: '3.8'

services:

  sql-server:
    user: root
    container_name: sql-server-2019-polytechnics-dev-1
    image: mcr.microsoft.com/mssql/server:2019-CU22-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - SQL_VOLUME_PATH=${SQL_VOLUME_PATH}
    ports:
      - "1433:1433"
    volumes:
      - ${SQL_VOLUME_PATH}:/var/opt/mssql/data
    networks:
      - polytechnics-network-dev

  web-api-polytechnics:
    build: 
      context: .
      dockerfile: ./WebApiMdm/dockerfile
    container_name: web-api-polytechnics-api-dev-1
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ConnectionString=Data Source=sql-server;Initial Catalog=master;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
    volumes:
      - ./WebApiMdm:/app/WebApiMdm
    depends_on:
      - sql-server
    networks:
      - polytechnics-network-dev
    stdin_open: true
    tty: true
    # command: ["bash"]

  angular-ui:
    build:
      context: .
      dockerfile: ./MvmNewUI/dockerfile
    container_name: angular-polytechnics-dev-1
    volumes:
      - ./MvmNewUI:/app/MvmNewUI
      - /app/MvmNewUI/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - web-api-polytechnics
    networks:
      - polytechnics-network-dev
    stdin_open: true
    tty: true
    #command: ["bash"]

networks:
  polytechnics-network-dev:
    driver: bridge