version: '3.8'

services:

  sql-server-prod:
    user: root
    container_name: sql-server-2019-polytechnics-prod-1
    image: mcr.microsoft.com/mssql/server:2019-CU22-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - SQL_VOLUME_PATH=${SQL_VOLUME_PATH}
    ports:
      - "1433:1433"
    volumes:
      - ${SQL_VOLUME_PATH}:/var/opt/mssql/data
    networks:
      - polytechnics-network-prod

  web-api-polytechnics-prod:
    build: 
      context: .
      dockerfile: ./WebApiMdm/dockerfile.prod
    container_name: web-api-polytechnics-api-prod-1
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ConnectionString=Data Source=sql-server-prod;Initial Catalog=master;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      - sql-server-prod
    networks:
      - polytechnics-network-prod
    # stdin_open: true
    # tty: true
    # command: ["bash"]

  angular-ui-prod:
    build:
      context: .
      dockerfile: ./MvmNewUI/dockerfile.prod
    container_name: angular-polytechnics-prod-1
    ports:
      - "1080:80"
    depends_on:
      - web-api-polytechnics-prod
    networks:
      - polytechnics-network-prod
    # stdin_open: true
    # tty: true

networks:
  polytechnics-network-prod:
    driver: bridge