# Using Node.js 18 Hydrogen LTS
FROM node:18.12.0

# Set the working directory inside the container
WORKDIR /app/MvmNewUI

# Install the Angular CLI globally in the container
RUN npm install -g @angular/cli@15.2.9

# Copy package.json and package-lock.json first to leverage Docker cache
COPY ./MvmNewUI/package*.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application to the container
COPY ./MvmNewUI ./

# Expose port 4200 for ng serve
EXPOSE 4200

# Start the Angular app
# ng serve --host 0.0.0.0 --poll=2000
CMD [ "ng", "serve", "--host", "0.0.0.0", "--poll=2000" ]
