# Build stage: Use Node.js to build the Angular app
FROM node:18.12.0 AS build

# Set the working directory inside the container
WORKDIR /app/MvmNewUI

# Install the Angular CLI globally in the container
RUN npm install -g @angular/cli@15.2.9

# Copy package.json and package-lock.json first to leverage Docker cache
COPY ./MvmNewUI/package*.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application to the container
COPY ./MvmNewUI ./

# Build the Angular app in production mode. This will create the /dist directory.
RUN ng build

# Production stage: Use NGINX to serve the built Angular app
FROM nginx:alpine

# Copy the built app from the build container
COPY --from=build /app/MvmNewUI/dist/mvm-new-ui /usr/share/nginx/html

# Expose port 80 (default port for NGINX)
EXPOSE 80

# NGINX will start automatically, so no need for a CMD
