# Use the official .NET 6 SDK image as the base image.
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

# Set the working directory in the container.
WORKDIR /app/WebApiMdm

# Copy the entire solution to the container.
COPY ./WebApiMdm ./

# Restore the NuGet packages at the solution level. 
RUN dotnet restore WebApiMdm.sln

# Build the application at the solution level.
RUN dotnet build WebApiMdm.sln

# Generate a development HTTPS certificate.
RUN dotnet dev-certs https -ep /https/aspnetapp.pfx -p devPassword

# Expose ports 5000(http) and 5001(https).
EXPOSE 5000
EXPOSE 5001

WORKDIR /app/WebApiMdm/WebApiMdm
# Define the entry point of the container.
# dotnet run
CMD ["dotnet", "run"]